app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

from app import db, login_manager

class Faculty(UserMixin, db.Model):
	__tablename__ = 'faculty'

	faculty_id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(60), index=True, unique=True)
	name = db.Column(db.String(50))
	password_hash = db.Column(db.String(128))
	#schedule = db.relationship('Schedule', backref = 'faculty_schedule', lazy='dynamic')

	@property
	def password(self):

		raise AttributeError('password is not a readable attribute.')

	@password.setter
	def password(self, password):

		self.password_hash = generate_password_hash(password)

	def verify_password(self, password):

		return check_password_hash(self.password_hash, password)

	def __repr__(self):
		return '<User: {}>'.format(username)

@login_manager.user_loader
def load_user(faculty_id):
    return Faculty.query.get(int(faculty_id))

class Batches(db.Model):
	__tablename__ = 'batches'

	batch_code = db.Column(db.Integer, primary_key=True)
	section = db.Column(db.String(2))
	semester = db.Column(db.Integer)
	#students_list = db.relationship('Student', backref='batch_student', lazy='dynamic')
	#faculty_list = db.relationship('Faculty', backref='batch_faculty', lazy='dynamic')

	def __repr__(self):
		return '<Batch: {}>'.format(section)

class Student(db.Model):
	__tablename__ = 'students'

	roll_no = db.Column(db.Integer, primary_key=True)
	batch_code = db.Column(db.Integer, db.ForeignKey('batches.batch_code'))
	name = db.Column(db.String(50))

	def __repr__(self):
		return '<Student: {}>'.format(roll_no)

class Schedule(db.Model):

	__tablename__ = 'schedule'
	weekday_temp = datetime.now().weekday()
	schedule_id = db.Column(db.Integer, primary_key=True)
	week_no = db.Column(db.Integer)
	weekday = db.Column(db.Integer, default=weekday_temp)
	batch_code = db.Column(db.Integer, db.ForeignKey('batches.batch_code'))
	period_number = db.Column(db.Integer)
	faculty_id = db.Column(db.Integer, db.ForeignKey('faculty.faculty_id'))
	subject = db.Column(db.String(5))

	def __repr__(self):
		return '<Week | Period No. : {}>'.format(week_no, period_number)


class Attendance(db.Model):
	__tablename__ = 'attendance'

	weekday_temp = datetime.now().weekday()
	date_temp = datetime.now()
	attendance_id = db.Column(db.Integer, primary_key=True)
	date = db.Column(db.DateTime, default=date_temp.date)
	week_no = db.Column(db.Integer)
	weekday = db.Column(db.Integer, default=weekday_temp)
	period_number = db.Column(db.Integer)
	faculty_id = db.Column(db.Integer, db.ForeignKey('faculty.faculty_id'))
	roll_no = db.Column(db.Integer, db.ForeignKey('students.roll_no'))
	status = db.Column(db.String(2))

	def __repr__(self):
		return '<Roll No | Status : {}>'.format(roll_no, status)

app/faculty/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, ValidationError, IntegerField, FileField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileRequired
from wtforms.fields.html5 import DateField

class GetStudentsAttendance(FlaskForm):
	section = StringField('Enter Section', validators=[DataRequired()])
	datefrom = DateField('From Date', validators=[DataRequired()], format='%Y-%m-%d')
	dateto = DateField('To Date', validators=[DataRequired()], format='%Y-%m-%d')
	submit = SubmitField('Submit')

class AddClass(FlaskForm):
	section = StringField('Enter Section Name', validators=[DataRequired()])
	semester = IntegerField('Enter Semester Number', validators=[DataRequired()])
	excel_file = FileField('Enter Student List',validators=[FileRequired()])
	submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import app_config
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap

db = SQLAlchemy()
login_manager = LoginManager()

def create_app(config_name):
	app = Flask(__name__, instance_relative_config = True)
	app.config.from_object(app_config[config_name])
	app.config.from_pyfile('config.py')
	db.init_app(app)
	login_manager.init_app(app)
	login_manager.login_message = "You must be logged in"
	login_manager.login_view = 'auth.login'
	migrate = Migrate(app, db)
	Bootstrap(app)

	from app import models

	from .auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint)

	from .api import api as api_blueprint
	app.register_blueprint(api_blueprint, url_prefix ='/api')

	from .hod import hod as hod_blueprint
	app.register_blueprint(hod_blueprint, url_prefix='/admin')

	from .faculty import faculty as faculty_blueprint
	app.register_blueprint(faculty_blueprint)

	return app

app/api/__init__.py
from flask import Blueprint
from flask_restful import Api

api = Blueprint('api', __name__)
rest = Api(api)

from . import views

app/api/views.py
from flask_restful import Api, Resource
from . import api, rest
from .. import db
from ..models import Schedule, Student, Attendance
from datetime import datetime

class Faculty_Schedule(Resource):
	"""docstring for Note"""
	def get(self, faculty_id):
		today_date = datetime.now().date()
		today_classes = Schedule.query.filter_by(faculty_id=faculty_id).filter_by(date_and_time=today_date).all()
		return {'notes':today_classes}

class Test(Resource):
	def get(self):
		hello = 'wahts up'
		return {'Hello':hello}

class Students(Resource):
	def get(self, batch_code):
		data=[]
		students_list = Student.query.filter_by(batch_code=batch_code).all()
		for a in students_list:
			data.append({
				'roll_no':a.roll_no,
				'name' : a.name
				})

		return {'status':'Good', 'students':data}

	def post(self):

		attendance = {'All details of of attendacne'}

		db.session.add(attendance)
		db.session.commit()
		return {'status': 'Attendace Done'}
class Attendance(Resource):
	def post(self):
		roll_no = request.form['roll_no']
		status = request.form['status']


rest.add_resource(Faculty_Schedule, '/faculty/schedule/<int:faculty_id>')
rest.add_resource(Students, '/students/list/<int:batch_code>')
rest.add_resource(Test, '/test')


#pbkdf2:sha256:50000$g2mwDcDJ$fd6fbb1398217e35b1cca2d5272517ce732c0cc107107b472447defdfbbd76cc

app/faculty/__init__.py
from flask import Blueprint

faculty = Blueprint('faculty', __name__)

from . import views

app/faculty/views.py
from flask import abort, render_template, flash, redirect, url_for
from flask_login import current_user, login_required
from datetime import datetime
from ..sql_queries import *
import sqlite3

from .. import db
from ..models import *
from . import faculty
from .forms import *

def query_attendance(section,from_date,to_date):
	with sqlite3.connect('instance/app.db') as conn:
		l=list()
		cur = conn.cursor()
		from_date = from_date + ' 00:00:00.000000'
		to_date = to_date + '00:00:00.000000'
		query = "select * from attendance where date between {0} and {1} ".format(from_date,to_date)
		cur.execute(query)
		data = cur.fetchall()
		conn.close()
	return data

@faculty.route('/')
@faculty.route('/index')
def index():
	return render_template('/faculty/index.html')

@faculty.route('/attendance', methods=['GET', 'POST'])
def get_attendance():
	current_date = datetime.now()
	form = GetStudentsAttendance()
	if form.validate_on_submit():
		section = form.section.data
		date_from = form.datefrom.data.strftime('%Y-%m-%d')
		date_to = form.dateto.data.strftime('%Y-%m-%d')
		print(query_attendance(section,date_from,date_to))

	return render_template('/faculty/get_attendance.html',form=form, students = None)

@faculty.route('/addstudents')
def add_students():
	form = AddClass()
	if form.validate_on_submit():
		file = form.excel_file.data
	return render_template('/faculty/add_class.html',form=form)

@faculty.route('/logout')
@login_required
def logout():

    logout_user()
    flash('You have successfully been logged out.')

    return redirect(url_for('auth.login'))

app/hod/__init__.py
from flask import Blueprint

hod = Blueprint('hod', __name__)

from . import views

app/hod/views.py
from flask import abort, render_template, flash, redirect, url_for
from flask_login import current_user, login_required

from .. import db
from ..models import *
from . import hod

def check_admin():
    if not current_user.is_admin:
        abort(403)

@hod.route('/index')
def admin_index():
	#check_admin()
	return render_template('/hod/hod_index.html')

@hod.route('/logout')
@login_required
def hod_logout():

    logout_user()
    flash('You have successfully been logged out.')

    return redirect(url_for('auth.login'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Add more meta tag -->
    <link rel="icon" href="../../favicon.ico">
    
    <title>Dashboard for Attendence Manager</title>
  <!-- Changed Title  -->
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Css file for Dashboard -->
    <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/logout">Logout</a></li>
          </ul>
          <div>  </div>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="{{ url_for('faculty.index') }}">Overview</a></li>
            <li><a href="{{ url_for('faculty.get_attendance') }}">Reports</a></li>
            <li><a href="{{ url_for('faculty.add_students') }}">Manange Students</a></li>
            <li><a href="#">Manange Attendance</a></li>
          </ul>
        </div>
        {% block content %}{% endblock %}      
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/templates/faculty/add_class.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Faculty Dashboard</h1>

          <h2 class="sub-header">Add Batch</h2>
          <div class="table-responsive">
            {{ wtf.quick_form(form) }}
          </div>
        </div>
{% endblock %}

app/templates/faculty/get_attendance.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Faculty Dashboard</h1>

          <h2 class="sub-header">Get Attendance</h2>
          <div class="table-responsive">
            {{ wtf.quick_form(form) }}
            {% if students %}
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
            {% endif %}
          </div>
        </div>
{% endblock %}

app/templates/faculty/index.html
{% extends "base.html" %}
{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Faculty Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
{% endblock %}

app/templates/hod/add_class.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Faculty Dashboard</h1>

          <h2 class="sub-header">Add Batch</h2>
          <div class="table-responsive">
            {{ wtf.quick_form(form) }}
          </div>
        </div>
{% endblock %}

app/templates/hod/add_faculty.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block content %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Faculty Dashboard</h1>

          <h2 class="sub-header">Add Batch</h2>
          <div class="table-responsive">
            {{ wtf.quick_form(form) }}
          </div>
        </div>
{% endblock %}

app/templates/hod_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('hod.hod_logout') }}">Logout</a></li>
          </ul>
          <div>  </div>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="#">Overview</a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Manage Faculty</a></li>
            <li><a href="#">Manange Students</a></li>
          </ul>
        </div>
        {% block content %}{% endblock %}      
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>